# Generated by Django 4.1 on 2022-09-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('empresa', models.CharField(max_length=30)),
                ('fecha_creacion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('nit', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('sector_productivo', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuarios', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('imagen', models.CharField(max_length=30)),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('rol', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id_movimientos', models.IntegerField(primary_key=True, serialize=False)),
                ('gastos', models.FloatField(max_length=30)),
                ('ingresos', models.FloatField(max_length=30)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api16.empleados')),
            ],
        ),
        migrations.AddField(
            model_name='empleados',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api16.empresa'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='id_usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api16.usuarios'),
        ),
    ]
