# Generated by Django 4.1 on 2022-09-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api16', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='sector_productivo',
            field=models.CharField(max_length=31),
        ),
    ]
