# Generated by Django 4.1 on 2022-09-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api16', '0002_alter_empresa_sector_productivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nit',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
