# Generated by Django 4.1 on 2022-09-13 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api16', '0005_movimientos_fecha_creacion_alter_empleados_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos',
            name='gastos',
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='id_empleado',
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='ingresos',
        ),
        migrations.AddField(
            model_name='movimientos',
            name='concepto',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movimientos',
            name='id_usuarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api16.usuarios'),
        ),
        migrations.AddField(
            model_name='movimientos',
            name='monto',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movimientos',
            name='tipo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
