# Generated by Django 4.1 on 2022-09-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api16', '0006_remove_movimientos_gastos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='imagen',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
