# Generated by Django 4.1 on 2022-09-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api16', '0007_alter_usuarios_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='id_movimientos',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
