# Generated by Django 4.1 on 2022-09-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api16', '0009_alter_movimientos_id_movimientos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='empresa',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id_empresa',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
