# Generated by Django 4.1 on 2022-09-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api16', '0010_alter_empleados_empresa_alter_empresa_id_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='empresa',
            field=models.CharField(max_length=30),
        ),
    ]
