# Generated by Django 4.1 on 2022-09-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api16', '0011_alter_empleados_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='empresa',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
